name-template: v$NEXT_PATCH_VERSION
tag-template: v$NEXT_PATCH_VERSION

change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
no-changes-template: "- No changes"
categories:
  - title: ":rocket: Enhancement"
    label: "feature :sparkles:"
template: |
  ***
  ### :zap: Changes
  $CHANGES
  ***
  ### :unicorn: Contributors
  Thank you $CONTRIBUTORS for the contributions! :trophy:
  ***